# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

julia:
  - 1.0
  - 1
  - nightly

os:
  - linux
  - osx
  - windows

arch:
  - x64
  - x86

matrix:
  exclude:
    - os: osx
      arch: x86
  fast_finish: true
  allow_failures:
    - julia: nightly

notifications:
  email: false

codecov: true
coveralls: true
